name: Build APT Repo

on:
  push:
    paths:
      - "debs/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev apt-utils gzip

      - name: Generate Packages
        run: |
          dpkg-scanpackages debs /dev/null > Packages
          gzip -9 -c Packages > Packages.gz
          apt-ftparchive release . > Release

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Packages Packages.gz Release

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update APT repository"

          git push origin HEAD:main
